### ISSUE TITLE
Multiplayer Matchmaking Example

### ISSUE THREAD

**Issue by CLoZengineer** [FeatureBaseDB/featurebase-examples#12]
### Overview
Matchmaking in games is primarily a matter of segmenting a large population down to finding a small well fit set. Sometimes as small a set as finding a single player for 1v1 competitive games.

Given the scope of potentially billions of players, needing to be broken down to a set of less than 100, this should be a solid example for FeatureBase.

### Scope
1. Generate a large dataset of players with traditional matchmaking data points
2. Build a simple API server that will take a player's id and return a set of potential matches

**Comment by kordless** [comment]
The challenge with this is to find enough data to show off the scaling of fb. Closing for now.
